### ISSUE TITLE
Pong Crash - Panic

### ISSUE THREAD

**Issue by markhughes** [grow-graphics/eg#3]
Tinkering around with this one, I found that the pong game crashes after about a minute of playing. 

Let me know if you need any more information! 

OS: macOS 14.2.1
godot --version: 4.2.2.stable.official.15073afe3
go version: go version go1.22.4 darwin/amd64
Version: 825f292 

```
Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org
Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon Pro 5500M
 
2024-08-14 16:00:10.909 godot[67047:77532129] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11990475a]

goroutine 17 [running, locked to thread]:
main.(*PongPaddle).OnAreaEntered(0xc0000c80e0, {{0x0?, 0xc0004cef90?}, 0x11acabc00?}, {{}, {{}, {0x0, 0xc0003c65c0}}})
        /Users/$USER/Projects/grow-grpahics-eg/2d/pong/pong.go:79 +0xda
reflect.Value.call({0x119db7000?, 0xc0000c80e0?, 0xc000200698?}, {0x119917c1d, 0x4}, {0xc0003001b0, 0x2, 0x118f4224c?})
        /usr/local/go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0x119db7000?, 0xc0000c80e0?, 0xc0004cef90?}, {0xc0003001b0?, 0xc00006a008?, 0xc0003c6580?})
        /usr/local/go/src/reflect/value.go:380 +0xb9
grow.graphics/gd.registerMethods.func1({{0x1695, 0xc0004cef90}, 0x11acabc00}, {0x119dd9ea0, 0xc000196450}, {0xc000610250, 0x1, 0x118f4e04d?})
        /Users/$USER/go/pkg/mod/grow.graphics/gd@v0.0.0-20240710064531-edc03e71dbe9/register_methods.go:77 +0x48b
grow.graphics/gd/gdextension.method_call(0x11?, 0x15, 0x7ff7bcce1610, 0x1, 0x7ff7bcce13d8, 0x7ff7bcce1380)
        /Users/$USER/go/pkg/mod/grow.graphics/gd@v0.0.0-20240710064531-edc03e71dbe9/gdextension/gdextension_interface.go:2599 +0x318
signal: abort trap```

**Replication steps:**
1. clone repo
2. change directory t o2d/pong
3. execute `gd` and it opens the project in godot
4. close project
5. execute `gd run`

**Expected results:**
The game runs

**What happens instead:**
The game crashes with the above error

**Comment by Splizard** [comment]
Thanks for reporting, this looks like it could be the same issue as https://github.com/grow-graphics/gd/issues/44
I've pushed a possible mitigation for this, I haven't been able to reproduce this issue on any of my machines so please do let me know if the issue still occurs with the latest commit.

**Comment by markhughes** [comment]
Nice one! I'll see if I can replicate it shortly.

**Comment by markhughes** [comment]
I can no longer replicate this one, nice!
